config/routes.rb
Rails.application.routes.draw do

  get       'my_login'  => 'sessions#new'
  get       'tamu_login'  => 'sessions#tamu_new'
  get       'my_logout'    => 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'welcome/index'

  match '/unapproved_completed_projects/' => 'projects#unapproved_completed_index', :as => :unapproved_completed_projects_index, via: [:get]
  match '/projects/:id/approve_completed' => 'projects#approve_completed', :as => :approve_completed_project, via: [:post]
  match '/projects/:id/unapprove_completed' => 'projects#unapprove_completed', :as => :unapprove_completed_project, via: [:post]
  match '/unapproved_projects/' => 'projects#unapproved_index', :as => :unapproved_projects_index, via: [:get]
  match '/projects/:id/approve' => 'projects#approve', :as => :approve_project, via: [:post]
  match '/projects/:id/unapprove' => 'projects#unapprove', :as => :unapprove_project, via: [:post]
  match '/projects/:id/join'    => 'projects#join', as: :join_project, via: [:post]
  match '/projects/:id/drop'    => 'projects#drop', as: :drop_project, via: [:post]
  resources :projects  # The priority is based upon order of creation: first created -> highest priority.
  
  match '/tamu_users/:id/make_admin' => 'tamu_users#make_admin', as: :make_user_admin, via: [:post]
  match '/tamu_users/:id/demote_admin' => 'tamu_users#demote_admin', as: :demote_admin, via: [:post]
  match '/unapproved_professors/' => 'tamu_users#unapproved_professor_index', :as => :unapproved_professors_index, via: [:get]
  match '/tamu_users/:id/approve_professor' => 'tamu_users#approve_professor', :as => :approve_professor, via: [:post]
  match '/tamu_users/:id/unapprove_professor' => 'tamu_users#unapprove_professor', :as => :unapprove_professor, via: [:post]
  match '/tamu_users/:id/block_user' => 'tamu_users#block_user', :as => :block_user, via: [:post]
  match '/tamu_users/:id/unblock_user' => 'tamu_users#unblock_user', :as => :unblock_user, via: [:post]
  resources :tamu_users

  match '/unapproved_agencies/' => 'agencies#unapproved_index', :as => :unapproved_agencies_index, via: [:get]
  match '/agencies/:id/approve' => 'agencies#approve', :as => :approve_agency, via: [:post]
  match '/agencies/:id/unapprove' => 'agencies#unapprove', :as => :unapprove_agency, via: [:post]
  resources :agencies

  root 'welcome#index'

end

app/models/tamu_user.rb
class TamuUser < ActiveRecord::Base
  
  def self.all_roles
    ["student","professor","unapproved_professor"]
  end
  
  def student?
    role == "student"
  end
  
  def professor?
    role == "professor"
  end

  def unapproved_professor?
    role == "unapproved_professor"
  end
  
  has_and_belongs_to_many :projects
  
  validates :name, presence: true
  validates :netid, presence: true
  validates :email, email_format: { message: "doesn't look like an email address" }, presence: true
  validates :role, :inclusion => { :in => TamuUser.all_roles }, presence: true
  validates :admin, :inclusion => {:in => [true, false]}
  validates :master_admin, inclusion: [true, false]
  validates :master_admin, exclusion: [true], if: 'not admin?'
end

app/controllers/tamu_users_controller.rb
class TamuUsersController < ApplicationController
    include TamuUsersHelper
    include ProjectsHelper
    
    before_action :admin_only, :only=>[:make_admin, :unapproved_professor_index, :approve_professor, :unapprove_professor]
    before_action :owner_only, :only=>[:edit, :update, :destroy]
    before_action :tamu_user_only, :only=>[:index]
    before_action :tamu_user_or_related, :only => [:show]
    before_action :new_tamu_user_only, :only => [:new, :create]
    before_action :master_admin_only, :only => [:demote_admin]
    skip_before_action :require_login, :only => [:new, :create]
    
    def tamu_user_params
      params.require(:tamu_user).permit(:name, :email, :role, :description)
    end
    def create_tamu_user_params
      params.require(:tamu_user).permit(:name, :email, :role, :netid).merge(netid: session_netid)
    end

    def index
        @tamu_users = list_users TamuUser.all
    end
    
    def unapproved_professor_index
        @tamu_users = list_users TamuUser.where(role: "unapproved_professor")
    end
    
    def approve_professor
        @professor = TamuUser.find(params[:id])
        @professor.role = "professor";
        @professor.save
        if TamuUser.where(role: "unapproved_professor").count > 0
            flash[:success] = "TamuUser '#{@professor.name}' approved as professor."
            redirect_to unapproved_professors_index_path
        else
            flash[:success] = "TamuUser '#{@professor.name}' approved as professor. All professors have been approved."
            redirect_to tamu_users_path
        end
    end
    
    def unapprove_professor
        @professor = TamuUser.find(params[:id])
        @professor.role = "unapproved_professor";
        @professor.save
        flash[:success] = "Tamu User '#{@professor.name}' unapproved as professor."
        redirect_to tamu_users_path
    end
    
    def block_user
        @tamu_user = TamuUser.find(params[:id])
        if !@tamu_user.admin?
            @tamu_user.blocked = true;
            @tamu_user.save
        end
        redirect_to tamu_user_path(@tamu_user)
    end
    
    def unblock_user
        @tamu_user = TamuUser.find(params[:id])
        @tamu_user.blocked = false;
        @tamu_user.save
        redirect_to tamu_user_path(@tamu_user)
    end
    
    def show
        @tamu_user = TamuUser.find params[:id]
        @projects = @tamu_user.projects
        @projects = sort_projects(@projects, params[:sort], params[:reverse])
    end
    
    def new
         @tamu_user = new_tamu_user_skeleton
    end
    
    def create
        #TODO: stop creating as faculty for now?
        @tamu_user = TamuUser.new create_tamu_user_params
        if @tamu_user.save
            log_in(@tamu_user)
            flash[:success] = "Profile for #{@tamu_user.name} was successfully created!"
            redirect_to tamu_user_path(@tamu_user)
        else
            model_failed_flash @tamu_user
            render action: "new"
        end
    end
    
    def destroy
        @tamu_user = TamuUser.find params[:id]
	redirect_to tamu_users_path, notice: "You can't delete master admins" and return if @tamu_user.master_admin?
        @tamu_user.destroy
        flash[:success] = "TAMU User '#{@tamu_user.name}' deleted."
        redirect_to tamu_users_path
    end
    
    def edit
        @tamu_user = TamuUser.find params[:id]
    end
    
    def update
        @tamu_user = TamuUser.find params[:id]
        new_params = tamu_user_params
        if @tamu_user.professor?
          new_params[:role] = "professor" if new_params[:role] == "unapproved_professor"
        else
          new_params[:role] = "unapproved_professor" if new_params[:role] == "professor"
        end


        if @tamu_user.update_attributes new_params
            flash[:success] = "# Profile was successfully updated."
            redirect_to tamu_user_path
        else
            model_failed_flash @tamu_user
            render action: "edit", id: @tamu_user.id
        end
    end

    def make_admin
        @tamu_user = TamuUser.find params[:id]
        @tamu_user.admin = true
        @tamu_user.save
        flash[:success] = "Successfully made #{@tamu_user.name} into an admin"
        redirect_to tamu_users_path
    end

    def demote_admin
        @tamu_user = TamuUser.find params[:id]
        if @tamu_user == current_user
          redirect_to tamu_users_path, notice: "You can't demote yourself" and return
        end
        @tamu_user.master_admin = false
        @tamu_user.admin = false
        @tamu_user.save
        flash[:success] = "#{@tamu_user.name} no longer an admin"
        redirect_to tamu_users_path
    end
    
    private

    def owner_only
        tamu_user = TamuUser.find params[:id]
        unless current_user == tamu_user
            redirect_to root_path, :alert => "Access denied."
        end
    end

    def tamu_user_or_related
        unless current_user.is_a?(TamuUser) ||
          (current_user.is_a?(Agency) && current_user.related_to_tamu_user?(params[:id]))
            redirect_to root_path, :alert => "Access denied."
        end
    end

    def new_tamu_user_only
      if logged_in? or (not cas_logged_in?)
          return redirect_to root_path, :alert => "Access denied."
      end
    end

    def list_users(list)
      list.order(:name).page(params[:page]).per(9)
    end
end

app/helpers/tamu_users_helper.rb
module TamuUsersHelper

  def new_tamu_user_skeleton
    netid = session_netid
    email = "#{netid}@tamu.edu"
    role = 'student' # hopefully we can look this up via netid later
    TamuUser.new(netid: netid, email: email, role: role, admin: false)
  end

  def toggle_admin_button(current, other, opts = {})
    if other.admin?
      if current.master_admin?
        demote_admin_button other.id, opts
      else
        "Admin"
      end
    else
      make_admin_button other.id, opts
    end
  end

  def make_admin_button(id, opts = {})
    opts.reverse_merge!(class: "btn btn-warning")
    button_to "Make Admin", make_user_admin_path(id), confirm: "Are you sure?", :class => opts
  end

  def demote_admin_button(id, opts = {})
    opts.reverse_merge!(class: "btn btn-danger")
    button_to "Remove Admin", demote_admin_path(id), confirm: "Are you sure?", :class => opts
  end

end

app/views/tamu_users/edit.html.haml
- tamu_user = TamuUserPresenter.new @tamu_user
%h1 Edit Profile

= form_tag tamu_user_path(@tamu_user), id: 'edit_user_form', :method => :put do

  = label :tamu_user, :name, 'Name'
  = text_field :tamu_user, 'name', required: true

  = label :tamu_user, :email, 'Email'
  = text_field :tamu_user, 'email', required: true, type: 'email'

  = label :tamu_user, :description, 'Description'
  = text_area :tamu_user, 'description', required: true

  = label :tamu_user, :role, 'Role'
  = tamu_user.role_select
  %br
  %br
  = submit_tag 'Save Changes', id: 'submit_user_form', :class=>"btn btn-primary"

app/views/tamu_users/index.html.haml
#headtitle All TAMU Users
%body
    #content
        %table{:border => 1, :width => "70%"}
            %tr{:height => "40px"}
                %th{:align=> "left"} Name
                - if @current_user.is_a?(TamuUser) and @current_user.admin?
                    %th{:align=> "left"} Admin Status
                %th User since
        
            - TamuUserPresenter.all(@tamu_users) do |tamu_user|
                %tr{:height => "40px"}
                    %td= tamu_user.profile
                    - if @current_user.is_a?(TamuUser) and @current_user.admin?
                        %td= toggle_admin_button @current_user, tamu_user, :class => "btn"
                    %td= tamu_user.date
        %p= paginate @tamu_users
        #footer

app/views/tamu_users/new.html.haml
%h1 Create your profile
/TODO

= form_tag tamu_users_path,id: 'new_tamu_user_form' do

  = label :tamu_user, :name, 'Name'
  = text_field :tamu_user, 'name', required: true

  = label :tamu_user, :email, 'Email'
  = text_field :tamu_user, 'email', required: true, type: 'email'

  = label :tamu_user, :role, 'Role' #TODO: rename this for users?
  = select :tamu_user, :role, [['Student', 'student'], ['Faculty', 'unapproved_professor']], class: "form-control"

  = hidden_field :tamu_user, :netid, value: session_netid
  %br
  %br
  = submit_tag 'Create profile',  :class=>'btn btn-primary'

app/views/tamu_users/show.html.haml
- tamu_user = TamuUserPresenter.new @tamu_user
.profile-header
  #headtitle
    #name= @tamu_user.name
%ul.nav.nav-tabs
  - if not @current_user.is_a?(Agency)
    %li.active
      %a{"data-toggle" => "tab", :href => "#my_projects"} Projects
    %li
      %a{"data-toggle" => "tab", :href => "#my_profile"} Profiles
  - else
    %li.active
      %a{"data-toggle" => "tab", :href => "#my_profile"} Profiles
.tab-content
  - if not @current_user.is_a?(Agency)
    #my_projects.tab-pane.fade.in.active
      %table{:border => 1, :width => "70%", :class=>"project_table"}
        %tr{:height => "10px"}
          %th{:align=> "left"}
            = tamu_user.profile "Project Name", params: sort_params(params, :name)
          %th{:align=> "left"} Description
          %th{:align=> "left"} Status
          %th{:align=> "left"} Tags
          %th{:align=> "left"}
            = tamu_user.profile "Date", params: sort_params(params, :date)
          %th{:align=> "left"}
            = tamu_user.profile "Agency", params: sort_params(params, :agency)
  
        - ProjectPresenter.all(@projects) do |project|
          %tr{:height => "10px"}
            %td= project.profile
            %td= project.description
            %td= project.status
            %td= project.tags
            %td= project.date
            %td= project.agency_profile
  
    #my_profile.tab-pane.fade
      %h3 Profile
      %h3 <i class="fa fa-child" aria-hidden="true"></i> Role:
      %p#role= tamu_user.role
  
      %h3 <i class="fa fa-envelope" aria-hidden="true"></i> Email:
      %p#email= tamu_user.email
  
      %h3 <i class='fa fa-commenting' aria-hidden='true'></i> About Me:
      %p#description=  tamu_user.description
      
      -if @current_user.is_a?(TamuUser) and @current_user.admin?
        %h3 Admin Status:
        %p#admin= toggle_admin_button(@current_user, tamu_user)
      
      - if @current_user == @tamu_user
        = tamu_user.edit_link
        
      - if @current_user.is_a?(TamuUser) and @current_user.admin?
        - if @tamu_user.unapproved_professor?
          = button_to 'Approve as Faculty', approve_professor_path(@tamu_user), :class=>"btn btn-success"
        - elsif @tamu_user.professor?
          = button_to 'Unapprove as Faculty', unapprove_professor_path(@tamu_user), :class=>"btn btn-danger"
        - if @tamu_user.blocked?
          = button_to 'Unblock User', unblock_user_path(@tamu_user), :class=>"btn btn-danger"
        - else
          = button_to 'Block User', block_user_path(@tamu_user), :class=>"btn btn-danger"
  - else
    #my_profile.tab-pane.fade.in.active
      %h3 Profile
      %h3 <i class="fa fa-child" aria-hidden="true"></i> Role:
      %p#role= tamu_user.role
  
      %h3 <i class="fa fa-envelope" aria-hidden="true"></i> Email:
      %p#email= tamu_user.email
  
      %h3 <i class='fa fa-commenting' aria-hidden='true'></i> About Me:
      %p#description=  tamu_user.description
      
      -if @current_user.is_a?(TamuUser) and @current_user.admin?
        %h3 Admin Status:
        %p#admin= toggle_admin_button(@current_user, tamu_user)
      
      - if @current_user == @tamu_user
        = tamu_user.edit_link
        
      - if @current_user.is_a?(TamuUser) and @current_user.admin?
        - if @tamu_user.unapproved_professor?
          = button_to 'Approve as Faculty', approve_professor_path(@tamu_user), :class=>"btn btn-success"
        - elsif @tamu_user.professor?
          = button_to 'Unapprove as Faculty', unapprove_professor_path(@tamu_user), :class=>"btn btn-danger"
        - if @tamu_user.blocked?
          = button_to 'Unblock User', unblock_user_path(@tamu_user), :class=>"btn btn-danger"
        - else
          = button_to 'Block User', block_user_path(@tamu_user), :class=>"btn btn-danger"

app/views/tamu_users/unapproved_professor_index.html.haml
#headtitle All Unapproved Faculty
%body
    #content
        %table{:border => 1, :width => "70%"}
            %tr{:height => "10px"}
                %th{:align=> "left"} Name
                - if @current_user.is_a?(TamuUser) and @current_user.admin?
                    %th{:align=> "left"} Professor Status
                    %th User since
        
            - TamuUserPresenter.all(@tamu_users) do |tamu_user|
                %tr{:height => "10px"}
                    %td= tamu_user.profile
                    %td= button_to "Approve as Faculty", approve_professor_path(tamu_user.id), confirm: "Are you sure?"
                    %td= tamu_user.date
        %p= paginate @tamu_users
        #footer