config/routes.rb
Rails.application.routes.draw do

  get       'my_login'  => 'sessions#new'
  get       'tamu_login'  => 'sessions#tamu_new'
  get       'my_logout'    => 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'welcome/index'

  match '/unapproved_completed_projects/' => 'projects#unapproved_completed_index', :as => :unapproved_completed_projects_index, via: [:get]
  match '/projects/:id/approve_completed' => 'projects#approve_completed', :as => :approve_completed_project, via: [:post]
  match '/projects/:id/unapprove_completed' => 'projects#unapprove_completed', :as => :unapprove_completed_project, via: [:post]
  match '/unapproved_projects/' => 'projects#unapproved_index', :as => :unapproved_projects_index, via: [:get]
  match '/projects/:id/approve' => 'projects#approve', :as => :approve_project, via: [:post]
  match '/projects/:id/unapprove' => 'projects#unapprove', :as => :unapprove_project, via: [:post]
  match '/projects/:id/join'    => 'projects#join', as: :join_project, via: [:post]
  match '/projects/:id/drop'    => 'projects#drop', as: :drop_project, via: [:post]
  resources :projects  # The priority is based upon order of creation: first created -> highest priority.
  
  match '/tamu_users/:id/make_admin' => 'tamu_users#make_admin', as: :make_user_admin, via: [:post]
  match '/tamu_users/:id/demote_admin' => 'tamu_users#demote_admin', as: :demote_admin, via: [:post]
  match '/unapproved_professors/' => 'tamu_users#unapproved_professor_index', :as => :unapproved_professors_index, via: [:get]
  match '/tamu_users/:id/approve_professor' => 'tamu_users#approve_professor', :as => :approve_professor, via: [:post]
  match '/tamu_users/:id/unapprove_professor' => 'tamu_users#unapprove_professor', :as => :unapprove_professor, via: [:post]
  match '/tamu_users/:id/block_user' => 'tamu_users#block_user', :as => :block_user, via: [:post]
  match '/tamu_users/:id/unblock_user' => 'tamu_users#unblock_user', :as => :unblock_user, via: [:post]
  resources :tamu_users

  match '/unapproved_agencies/' => 'agencies#unapproved_index', :as => :unapproved_agencies_index, via: [:get]
  match '/agencies/:id/approve' => 'agencies#approve', :as => :approve_agency, via: [:post]
  match '/agencies/:id/unapprove' => 'agencies#unapprove', :as => :unapprove_agency, via: [:post]
  resources :agencies

  root 'welcome#index'

end

app/models/agency.rb
class Agency < ActiveRecord::Base
  has_many :projects
  has_many :tamu_users, through: :projects

  validates :name, presence: true
  validates :email, email_format: { message: "doesn't look like an email address" }, presence: true
  validates :phone_number, format: { with: /\d{3}-\d{3}-\d{4}/, message: "bad format" }, :allow_blank => true
  validates :approved, :inclusion => {:in => [true, false]}

  def self.create_with_omniauth(auth)
    parameters = {:provider => auth["provider"], :uid => auth["uid"]}
    #parameters[:approved] = false

    assign_if_not_nil(parameters, :email, auth['info']['email'])
    assign_if_not_nil(parameters, :name, auth['info']['name'])
    #assign_if_not_nil(parameters, :location, auth['info']['location'])
    assign_if_not_nil(parameters, :image_url, auth['info']['image'])
    #assign_if_not_nil(parameters, :url, auth['info']['urls']['Google'])

    Agency.create!(parameters)
  end

  def related_to_tamu_user?(id)
    tamu_users.where(id: id).any?
  end

  private
  def self.assign_if_not_nil(hash, attribute, value)
    hash[attribute] = value unless value.nil?
  end
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
    
    before_action :admin_only, :only=>[:unapproved_index, :unapprove, :approve]
    before_action :tamu_user_only, :only=>[:index]
    before_action :tamu_user_or_owner_only, :only=>[:show]
    
    before_action :owner_only, :only=>[:edit, :update, :destroy]

    def agency_params
      params.require(:agency).permit(:name, :email, :phone_number)
    end
    
    def index
        @agencies = list_agencies Agency.where(approved: true)
    end
    
    def unapproved_index
        @agencies = list_agencies Agency.where(approved: false)
    end
    
    def show
        @agency = Agency.find params[:id]
        if user_should_not_see? @agency
          redirect_to agencies_path
        end
    end

    def edit
        @agency = Agency.find params[:id]
    end

    def update
        @agency = Agency.find params[:id]
        if @agency.update_attributes(agency_params)
            flash[:success] = "# Profile was successfully updated."
            redirect_to agency_path
        else
          model_failed_flash @agency
          render action: "edit", id: @agency.id
        end
    end
    
    def approve
        @agency = Agency.find(params[:id])
        @agency.approved = true;
        @agency.save
        if Agency.where(approved: false).count > 0
            flash[:success] = "Agency '#{@agency.name}' approved."
            redirect_to unapproved_agencies_index_path
        else
            flash[:success] = "Agency '#{@agency.name}' approved. All agencies have been approved."
            redirect_to agencies_path
        end
    end
    
    def unapprove
        @agency = Agency.find(params[:id])
        @agency.approved = false;
        @agency.save
        flash[:success] = "Agency '#{@agency.name}' unapproved."

        @agency.projects.each do |project|
          project.approved = false;
          project.save
        end

        redirect_to agencies_path
    end
    
    private

    def owner_only
        agency = Agency.find params[:id]
        unless current_user == agency
            redirect_to root_path, :alert => "Access denied."
        end
    end
    
    def tamu_user_or_owner_only
        agency = Agency.find(params[:id])
        unless current_user.is_a?(TamuUser) or agency == current_user
            redirect_to root_path, :alert => "Access denied."
        end
    end

    def list_agencies(list)
      list.order(:name).page(params[:page]).per(9)
    end
    
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/views/agencies/edit.html.haml
%h1 Edit Profile

= form_tag agency_path(@agency), id: 'edit_agency_form', :method => :put do

  = label :agency, :name, 'Name'
  = text_field :agency, 'name'
  = label :agency, :email, 'Email'
  = text_field :agency, 'email'
  = label :agency, :phone_number, 'Phone Number'
  = text_field :agency, 'phone_number'
  %p
  = submit_tag 'Save Changes', id: 'submit_agency_form', :class=>"btn btn-primary"

app/views/agencies/index.html.haml
#headtitle All Agencies
%body
    #content
        #left{:float => "left", :width => "30%"}
        #right
            %table{:border => 1, :width => "70%"}
                %tr{:height => "10px"}
                    %th{:align=> "left"} Name
                    - if @current_user.is_a?(TamuUser) and @current_user.admin?
                        %th{:align=> "left"} Unapprove Agency
            
                - @agencies.each do |agency|
                    %tr{:height => "10px"}
                        %td= link_to agency.name, agency_path(agency.id)
                        - if @current_user.is_a?(TamuUser) and @current_user.admin?
                            %td= button_to 'Unapprove Agency', unapprove_agency_path(agency)
        %p=paginate @agencies
        #footer

app/views/agencies/show.html.haml
.profile-header
  #headtitle
    #name= @agency.name
  #profile-edit
    -if @current_user == @agency
      <i class="fa fa-pencil" aria-hidden="true"></i>
      = link_to 'Edit Profile', edit_agency_path(@agency.id)
%ul.nav.nav-tabs
  %li.active
    %a{"data-toggle" => "tab", :href => "#my_projects"} My Projects
  %li
    %a{"data-toggle" => "tab", :href => "#my_profile"} My Profiles

.tab-content
  #my_projects.tab-pane.fade.in.active
    %table{:border => 1, :width => "70%", :class => "project_table"}
      %tr
        %th Project Name
        %th Description
        %th Status
        %th Tags
        %th Date

      - @agency.projects.each do |project|
        %tr{:height => "10px"}
          %td.name
            .name=link_to project.name, project_path(project)
          %td.description
            .description=project.description
          %td= project.status
          %td= project.tags.join ", "
          %td= project.created_at.to_date
    - if @current_user == @agency && @current_user.approved?
      %p
        = button_to 'Create Project', new_project_path, class: "btn btn-primary", method: :get
  #my_profile.tab-pane.fade
    %h3 My Profile
    %p= image_tag("#{@agency.image_url}")

    %h3 <i class="fa fa-envelope" aria-hidden="true"></i> Email:
    %p#email=  @agency.email

    
    
    %h3 <i class="fa fa-phone" aria-hidden="true"></i> Phone number:
    %p#phone_number=  @agency.phone_number

    - if @current_user.is_a?(TamuUser) and @current_user.admin?
      - if !@agency.approved
        = button_to 'Approve Agency', approve_agency_path(@agency),:class=>"btn btn-primary"
      - else
        = button_to 'Unapprove Agency', unapprove_agency_path(@agency),:class=>"btn btn-warning"

app/views/agencies/unapproved_index.html.haml
#headtitle All Unapproved Agencies
%body
    #content
        %table{:border => 1, :width => "70%"}
            %tr{:height => "10px"}
                %th{:align=> "left"} Name
                %th{:align=> "left"} Approve Agency
        
            - @agencies.each do |agency|
                %tr{:height => "10px"}
                    %td= link_to agency.name, agency_path(agency.id)
                    %td= button_to 'Approve', approve_agency_path(agency)
        %p=paginate @agencies
        #footer