config/routes.rb
Rails.application.routes.draw do

  get       'my_login'  => 'sessions#new'
  get       'tamu_login'  => 'sessions#tamu_new'
  get       'my_logout'    => 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'welcome/index'

  match '/unapproved_completed_projects/' => 'projects#unapproved_completed_index', :as => :unapproved_completed_projects_index, via: [:get]
  match '/projects/:id/approve_completed' => 'projects#approve_completed', :as => :approve_completed_project, via: [:post]
  match '/projects/:id/unapprove_completed' => 'projects#unapprove_completed', :as => :unapprove_completed_project, via: [:post]
  match '/unapproved_projects/' => 'projects#unapproved_index', :as => :unapproved_projects_index, via: [:get]
  match '/projects/:id/approve' => 'projects#approve', :as => :approve_project, via: [:post]
  match '/projects/:id/unapprove' => 'projects#unapprove', :as => :unapprove_project, via: [:post]
  match '/projects/:id/join'    => 'projects#join', as: :join_project, via: [:post]
  match '/projects/:id/drop'    => 'projects#drop', as: :drop_project, via: [:post]
  resources :projects  # The priority is based upon order of creation: first created -> highest priority.
  
  match '/tamu_users/:id/make_admin' => 'tamu_users#make_admin', as: :make_user_admin, via: [:post]
  match '/tamu_users/:id/demote_admin' => 'tamu_users#demote_admin', as: :demote_admin, via: [:post]
  match '/unapproved_professors/' => 'tamu_users#unapproved_professor_index', :as => :unapproved_professors_index, via: [:get]
  match '/tamu_users/:id/approve_professor' => 'tamu_users#approve_professor', :as => :approve_professor, via: [:post]
  match '/tamu_users/:id/unapprove_professor' => 'tamu_users#unapprove_professor', :as => :unapprove_professor, via: [:post]
  match '/tamu_users/:id/block_user' => 'tamu_users#block_user', :as => :block_user, via: [:post]
  match '/tamu_users/:id/unblock_user' => 'tamu_users#unblock_user', :as => :unblock_user, via: [:post]
  resources :tamu_users

  match '/unapproved_agencies/' => 'agencies#unapproved_index', :as => :unapproved_agencies_index, via: [:get]
  match '/agencies/:id/approve' => 'agencies#approve', :as => :approve_agency, via: [:post]
  match '/agencies/:id/unapprove' => 'agencies#unapprove', :as => :unapprove_agency, via: [:post]
  resources :agencies

  root 'welcome#index'

end

app/models/project.rb
class Project < ActiveRecord::Base

  def self.all_statuses
    ["completed","cancelled","open", "unapproved_completed"]
  end

  def agency_name
    agency.name
  end

  belongs_to :agency
  has_and_belongs_to_many :tamu_users

  validates :name, presence: true
  validates :status, :inclusion => { :in => Project.all_statuses }, presence: true
  validates :approved, :inclusion => {:in => [true, false]}
  serialize :tags, Array

  def completed?
    status == "completed"
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    include ProjectsHelper
    
    before_action :admin_only, :only=>[:unapproved_index, :unapprove, :approve, :unapproved_completed_index, :unapprove_completed, :approve_completed]
    before_action :agency_only, :only=>[:new, :create, :edit, :update, :destroy]
    before_action :owner_only, :only=>[:edit, :update, :destroy]
    before_action :tamu_user_or_owner_only, :only => [:show]
    before_action :tamu_user_only, :only=>[:index, :join, :drop]
    
    def project_params
        params[:project][:tags] = params[:project][:tags].split(/[\s,]+/)
        params.require(:project).permit(:name, :description, :status, :approved, 'tags'=> [])
    end
    
    def index
        @projects = Project.where(approved: true)

        if params[:search]
            session[:search] = params[:search]
        end

        if session[:search] && session[:search]['value'] != ""
            @search_value = session[:search]['value']
            @search_type = session[:search]['type']

            search_regex = Regexp.new(Regexp.escape(@search_value), "i")

            @projects = @projects.select do |project|
                if @search_type == "tags"
                    project.tags.grep(search_regex).any?
                else
                    project.send(@search_type) =~ search_regex
                end
            end
        end

        @projects = list_projects(@projects)
    end

    def unapproved_index
        @projects = list_projects Project.where(approved: false)
    end
    
    def unapproved_completed_index
      @projects = Project.where(status: "unapproved_completed")
      @projects = list_projects @projects
    end
   
    def show
      @project = Project.find(params[:id])
      if user_should_not_see? @project
        redirect_to projects_path
      end
    end
   
    def new
        @project = Project.new
    end
   
    def create
        @project = current_user.projects.build(project_params.merge(status: "open"))
        
        if @project.save
            flash[:success] = "#{@project.name} was successfully created."
            redirect_to project_path(@project)
        else
            model_failed_flash @project
            render action: "new"
        end
    end
   
    def edit
        @project = Project.find(params[:id])
    end
   
    def update
        @project = Project.find(params[:id])
        new_params = project_params
        if new_params[:status] == "completed"
            new_params[:status] = "unapproved_completed"
        end
        was_completed = @project.completed?
        
        if @project.update_attributes(new_params)
            if was_completed
              flash[:success] = "#{@project.name} was successfully updated and will need reapproval for completition."
            else
              flash[:success] = "#{@project.name} was successfully updated."
            end
            redirect_to project_path
        else
            model_failed_flash @project
            render action: "edit"
        end
    end
   
    def destroy
        @project = Project.find(params[:id]).destroy
        flash[:notice] = "Project '#{@project.name}' deleted."
        redirect_to projects_path
    end
    
    def approve
        @project = Project.find(params[:id])
        @project.approved = true;
        @project.save
        
        if Project.where(approved: false).count > 0
            flash[:success] = "Project '#{@project.name}' approved."
            redirect_to unapproved_projects_index_path
        else
            flash[:success] = "Project '#{@project.name}' approved. All projects have been approved."
            redirect_to projects_path
        end
    end
    
    def unapprove
        @project = Project.find(params[:id])
        @project.approved = false;
        @project.save
        flash[:success] = "Project '#{@project.name}' unapproved."
        redirect_to projects_path
    end
    
    def approve_completed
        @project = Project.find(params[:id])
        @project.status = "completed";
        @project.save
        
        if Project.where(status: "unapproved_completed").count > 0
            flash[:success] = "Project '#{@project.name}' completion approved."
            redirect_to unapproved_completed_projects_index_path
        else
            flash[:success] = "Project '#{@project.name}' approved. All projects have been approved."
            redirect_to projects_path
        end
    end
    
    def unapprove_completed
        @project = Project.find(params[:id])
        #@project.status = "open"
        @project.status = "unapproved_completed"
        if @project.save
          flash[:success] = "Project '#{@project.name}' completion unapproved."
        end
        redirect_to projects_path
    end

    def join
        @project = Project.find(params[:id])
        redirect_to projects_path and return unless @project.approved
        redirect_to project_path(@project) and return if @project.completed?

        if @project.tamu_users.include? current_user
            return redirect_to project_path(@project), notice: "You've already joined this project"
        end

        @project.tamu_users << current_user
        flash[:success] =  "Successfully joined #{@project.name}!"
        redirect_to project_path(@project)
    end

    def drop
        @project = Project.find(params[:id])
        redirect_to projects_path and return unless @project.approved
        redirect_to project_path(@project) and return if @project.completed?

        if not @project.tamu_users.include? current_user
            return redirect_to project_path(@project), notice: "You're not working on this project"
        end

        @project.tamu_users.delete(current_user)
        flash[:success] =  "Successfully dropped #{@project.name}!"
        redirect_to project_path(@project)
    end
    
    private

    def agency_only
      unless current_user.is_a?(Agency)
          redirect_to root_path, :alert => "Access Denied"
      end
    end
    
    def owner_only
        project = Project.find(params[:id])
        unless current_user == project.agency
            redirect_to root_path, :alert => "Access denied."
        end
    end

    def tamu_user_or_owner_only
      project = Project.find(params[:id])
      unless current_user.is_a?(TamuUser) or project.agency == current_user
        redirect_to root_path, :alert => "Access denied."
      end
    end

    def list_projects(projects)
      sorted = sort_projects(projects, params[:sort], params[:reverse])
      Kaminari.paginate_array(sorted).page(params[:page]).per(5)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
    def sort_projects(projects, sort, reverse = false)
        case sort
        when "name"
            projects = projects.sort_by {|project| project.name}
        when "date"
            projects = projects.sort_by {|project| project.created_at}
        when "agency"
            projects = projects.sort_by {|project| project.agency.name}
        end

        if reverse
          projects.reverse
        else
          projects
        end
    end
end

app/views/projects/edit.html.haml
- project = ProjectPresenter.new @project
-# edit.html.haml using partial

%h1 Edit Existing Project

= form_tag project_path(@project), id: 'edit_project_form', :method => :put do

  = label :project, :name, 'Name'
  = text_field :project, 'name', required: true

  = label :project, :description, 'Description'
  = text_area :project, 'description', :rows => 7, :cols=>70, placeholder: "Enter project description"

  = label :project, :tags, 'Tags'
  = text_field :project, 'tags'

  = label :project, :status, 'Status'
  = project.status_select
  %br
  = submit_tag 'Save Changes', id: 'submit_project_form' , :class=>'btn btn-primary'

app/views/projects/index.html.haml
#headtitle= link_to "All Projects", projects_path(search: {'value' => ""})

!!!

#content
    #left{:float => "left", :width => "30%"}
        = form_tag projects_path, :method => :get do
            = text_field :search, "value", value: @search_value
            %select{ :name => "search[type]", id: 'search_type', :class=>'styled-select' }
                %option{:value => "name", selected: @search_type == "name" }= "Name"
                %option{:value => "description", selected: @search_type == "description" }= "Description"
                %option{:value => "status", selected: @search_type == "status" }= "Status"
                %option{:value => "tags", selected: @search_type == "tags" }= "Tags"
                %option{:value => "agency_name", selected: @search_type == "agency_name" }= "Agency"

            = submit_tag 'Search',:class=>'btn btn-primary'
        %br
        %br
    #right
        %table{:border => 1, :width => "100%", :class => "project_table"}
            %tr{:height => "10px"}
                %th{:align=> "left"}
                    = link_to "Project Name", projects_path(sort_params params, :name)
                %th{:align=> "left"} Description
                %th{:align=> "left"} Status
                %th{:align=> "left"} Tags
                %th{:align=> "left"}
                    = link_to "Agency", projects_path(sort_params params,  :agency)
                %th{:align=> "left"}
                    = link_to "Date", projects_path(sort_params params,  :date)
                - if @current_user.is_a?(TamuUser) and @current_user.admin?
                    %th{:align=> "left"} Unapprove Project
        
            - ProjectPresenter.all(@projects) do |project|
                %tr{:height => "10px"}
                    %td= project.profile
                    %td= project.description
                    %td= project.status
                    %td= project.tags
                    %td= project.agency_profile
                    %td= project.date
                    - if @current_user.is_a?(TamuUser) and @current_user.admin?
                        %td= button_to 'Unapprove', unapprove_project_path(project.id)
    %p= paginate @projects
    #footer

app/views/projects/new.html.haml
%h1 Create New Projects

= form_tag projects_path,id: 'new_project_form' do

  = label :project, :name, 'Name'
  = text_field :project, 'name', required: true

  = label :project, :description, 'Description'
  = text_area :project, 'description', :rows => 7, :cols=>70, placeholder: "Enter project description"

  = label :project, :tags, 'Tags'
  = text_field :project, 'tags'

  = hidden_field :project, 'status', value:'open'
  %br
  %br
  = submit_tag 'Save Changes',  :class=>'btn btn-primary'

app/views/projects/show.html.haml
- project = ProjectPresenter.new @project
.profile-header
    #headtitle
        #name Details about #{project.name}

%h3 Description:
%p#description= project.description
#black-line
%h3 Tags:
%p#tags= project.tags
#black-line
%h3 Status:
%p#status= project.status
#black-line
%h3 Agency:
%p#agency= project.agency_profile        
- if not @project.tamu_users.empty?
    %h3 Contributers:
    #tamu_users
        %table{:border => 1, :width => "70%", :class=>"view_tables"}
            %tr{height: "10px"}
            %th{align: "left"} User Name
            %th{align: "left"} Role
            %th User since

            - TamuUserPresenter.all(@project.tamu_users) do |tamu_user|
                %tr{height: "10px"}
                    %td=tamu_user.profile
                    %td=tamu_user.role
                    %td=tamu_user.date
#black-line    
%p
- if @current_user == @project.agency
    #edit-delete
    = project.edit_button class: "btn btn-primary"
    = button_to 'Delete', project_path(@project), :method => :delete, :confirm => 'Are you sure?', :id=>"delete", :class=>"btn btn-danger"
- if not project.completed? and @current_user.is_a?(TamuUser)
    - if @current_user.projects.include?(@project)
        #drop-project
        %br
        = button_to 'Drop Project', drop_project_path(@project),:class=>"btn btn-primary"
    - else
        #join-project
        = button_to 'Join Project', join_project_path(@project),:class=>"btn btn-primary"
- if @current_user.is_a?(TamuUser) and @current_user.admin?
    - if !@project.approved
        = button_to 'Approve Project', approve_project_path(@project),:class=>"btn btn-warning"
    - else
        = button_to 'Unapprove Project', unapprove_project_path(@project),:class=>"btn btn-warning"
- if @current_user.is_a?(TamuUser) and @current_user.admin?
    - if @project.status == "completed"
        = button_to 'Unapprove Project Completion', unapprove_completed_project_path(@project),:class=>"btn btn-warning"
    - elsif @project.status == "unapproved_completed"
        = button_to 'Approve Project Completion', approve_completed_project_path(@project),:class=>"btn btn-warning"
        

%br
- if @current_user.is_a?(TamuUser)
    = button_to 'Back to project list', projects_path,:class=>"btn btn-info"

app/views/projects/unapproved_completed_index.html.haml
!!!
-#%head
-#    %h1 TAMU Non-Profit Projects Collect System
-#%body
#headtitle All Completed Projects Pending Approval
#content
    #left{:float => "left", :width => "30%"}
        // -#%p
        // %input{:size => "15", :maxlength => "100", :name => "search_index", :type => "text", :value => ""}/
        // %br
        // %button{:type => "button"} Search
        // -#%p
        // -#= link_to "Create Project", new_project_path
        // -#%br
        // -#%a{:href => "url"} Advanced Search
        // %p
        // = link_to "Create Project", new_project_path
        // %br
        // -#%p
        // = link_to "My page", tamu_user_path(1)
        // -#%br
        // %br
    #right
        %table{:border => 1, :width => "70%", :class => "project_table"}
            %tr{:height => "10px"}
                %th{:align=> "left"}
                    = link_to "Project Name", unapproved_completed_projects_index_path(sort_params params, :name)
                %th{:align=> "left"} Description
                %th{:align=> "left"} Status
                %th{:align=> "left"} Tags
                %th{:align=> "left"}
                    = link_to "Agency", unapproved_completed_projects_index_path(sort_params params,  :agency)
                %th{:align=> "left"}
                    = link_to "Date", unapproved_completed_projects_index_path(sort_params params,  :date)
                %th{:align=> "left"} Approve Completion
        
            - ProjectPresenter.all(@projects) do |project|
                %tr{:height => "10px"}
                    %td= project.profile
                    %td= project.description
                    %td= project.status
                    %td= project.tags
                    %td= project.agency_profile
                    %td= project.date
                    %td= button_to 'Approve', approve_completed_project_path(project.id)
    %p= paginate @projects
    #footer

app/views/projects/unapproved_index.html.haml
!!!

#headtitle All Unapproved Projects
#content
    #left{:float => "left", :width => "30%"}
    #right
        %table{:border => 1, :width => "70%", :class => "project_table"}
            %tr{:height => "10px"}
                %th{:align=> "left"}
                    = link_to "Project Name", unapproved_projects_index_path(sort_params params, :name)
                %th{:align=> "left"} Description
                %th{:align=> "left"} Status
                %th{:align=> "left"} Tags
                %th{:align=> "left"}
                    = link_to "Agency", unapproved_projects_index_path(sort_params params,  :agency)
                %th{:align=> "left"}
                    = link_to "Date", unapproved_projects_index_path(sort_params params,  :date)
                %th{:align=> "left"} Approve Project
        
            - ProjectPresenter.all(@projects) do |project|
                %tr{:height => "10px"}
                    %td= project.profile
                    %td= project.description
                    %td= project.status
                    %td= project.tags
                    %td= project.agency_profile
                    %td= project.date
                    %td= button_to 'Approve', approve_project_path(project.id), class: "approve_proj"
    %p= paginate @projects
    #footer