config/routes.rb
Rails.application.routes.draw do

  get       'my_login'  => 'sessions#new'
  get       'tamu_login'  => 'sessions#tamu_new'
  get       'my_logout'    => 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'welcome/index'

  match '/unapproved_completed_projects/' => 'projects#unapproved_completed_index', :as => :unapproved_completed_projects_index, via: [:get]
  match '/projects/:id/approve_completed' => 'projects#approve_completed', :as => :approve_completed_project, via: [:post]
  match '/projects/:id/unapprove_completed' => 'projects#unapprove_completed', :as => :unapprove_completed_project, via: [:post]
  match '/unapproved_projects/' => 'projects#unapproved_index', :as => :unapproved_projects_index, via: [:get]
  match '/projects/:id/approve' => 'projects#approve', :as => :approve_project, via: [:post]
  match '/projects/:id/unapprove' => 'projects#unapprove', :as => :unapprove_project, via: [:post]
  match '/projects/:id/join'    => 'projects#join', as: :join_project, via: [:post]
  match '/projects/:id/drop'    => 'projects#drop', as: :drop_project, via: [:post]
  resources :projects  # The priority is based upon order of creation: first created -> highest priority.
  
  match '/tamu_users/:id/make_admin' => 'tamu_users#make_admin', as: :make_user_admin, via: [:post]
  match '/tamu_users/:id/demote_admin' => 'tamu_users#demote_admin', as: :demote_admin, via: [:post]
  match '/unapproved_professors/' => 'tamu_users#unapproved_professor_index', :as => :unapproved_professors_index, via: [:get]
  match '/tamu_users/:id/approve_professor' => 'tamu_users#approve_professor', :as => :approve_professor, via: [:post]
  match '/tamu_users/:id/unapprove_professor' => 'tamu_users#unapprove_professor', :as => :unapprove_professor, via: [:post]
  match '/tamu_users/:id/block_user' => 'tamu_users#block_user', :as => :block_user, via: [:post]
  match '/tamu_users/:id/unblock_user' => 'tamu_users#unblock_user', :as => :unblock_user, via: [:post]
  resources :tamu_users

  match '/unapproved_agencies/' => 'agencies#unapproved_index', :as => :unapproved_agencies_index, via: [:get]
  match '/agencies/:id/approve' => 'agencies#approve', :as => :approve_agency, via: [:post]
  match '/agencies/:id/unapprove' => 'agencies#unapprove', :as => :unapprove_agency, via: [:post]
  resources :agencies

  root 'welcome#index'

end

app/views/layouts/application.html.haml
%html
  %head
    %title TAMU Projects Collectiton System
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    #maroon_top
      #title_padding
        /%h2.title Texas A&M Projects Collection System
        =link_to image_tag('logo.png', :height => "12%"), root_path
      .top-header
        #a-maroon
          = link_to '<i class="fa fa-home" aria-hidden="true"></i> Home'.html_safe, root_path
          - if !logged_in?
            #login
              = link_to '<i class="fa fa-sign-out" aria-hidden="true"></i>Login'.html_safe, my_login_path
          - else 
            - if @current_user.is_a?(TamuUser)
              
              = link_to '<i class="fa fa-users" aria-hidden="true"></i> My Page'.html_safe, tamu_user_path(@current_user.id)
              
              = link_to '<i class="fa fa-graduation-cap" aria-hidden="true"></i> TAMU Users'.html_safe, tamu_users_path
              
              = link_to '<i class="fa fa-building" aria-hidden="true"></i> Agencies'.html_safe, agencies_path
              
              = link_to '<i class="fa fa-sticky-note" aria-hidden="true"></i> Projects'.html_safe, projects_path
              - if @current_user.admin?
                
                = link_to '<i class="fa fa-exclamation" aria-hidden="true"></i> Unapproved Agencies'.html_safe, unapproved_agencies_index_path
                
                = link_to '<i class="fa fa-exclamation" aria-hidden="true"></i> Unapproved Projects'.html_safe, unapproved_projects_index_path
                
                = link_to '<i class="fa fa-exclamation" aria-hidden="true"></i> Unapproved Faculty'.html_safe, unapproved_professors_index_path
                
                = link_to '<i class="fa fa-exclamation" aria-hidden="true"></i> Completed Projects'.html_safe, unapproved_completed_projects_index_path
            - else
              
              = link_to '<i class="fa fa-user" aria-hidden="true"></i> My Page'.html_safe, agency_path(@current_user.id)
            #logout
              = link_to '<i class="fa fa-sign-out" aria-hidden="true"></i>Log out'.html_safe, current_user.is_a?(TamuUser) ? '/logout' : my_logout_path, :onclick=>'logout()'
      #login-as
        - if logged_in?
          Logged in as #{current_user.name}
    #main
      #layoutcenter
        - if flash[:notice]
          #notice.message!= flash[:notice]
        - elsif flash[:warning]
          #warning.message!= flash[:warning]
        - elsif flash[:success]
          #success.message!= flash[:success]

        = yield
    #maroon_footer
      <i class="fa fa-copyright" aria-hidden="true"></i> 2016 Texas A&M University 
      %br
      Developed By:  Daniel Latypov, Brennen Taylor, Evan Feiereisel, Jeremy Tso, Jerry Yiu, Bill Cheng